use_frameworks!

target 'CGLockData_Example' do
  pod 'CGLockData', :path => '../'

  target 'CGLockData_Tests' do
    inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
  end
end
